/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filerenamer.ui;

import javax.swing.JFileChooser;
import javax.swing.DefaultListModel;
import java.io.File;
import java.nio.file.Files;
import java.io.IOException;
import filerenamer.logic.RenameStrategy;
import filerenamer.logic.RandomNumberStrategy;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import filerenamer.logic.NumberingStrategy;
import filerenamer.logic.PrefixStrategy;
import filerenamer.logic.SuffixStrategy;
import filerenamer.logic.WordNumberStrategy;
import filerenamer.logic.RemoveSubstringStrategy;
import filerenamer.logic.RemoveCharsStrategy;
import filerenamer.logic.NaturalOrderComparator;
import filerenamer.logic.NumberingFromStrategy;
import java.util.Arrays;
import java.util.Comparator;
/**
 *
 * @author siste
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    
    private File selectedSourceFolder;
    private File selectedDestFolder;
    private static final String APP_NAME = "File Renamer";
    private static final String APP_VERSION = "1.8";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
    initComponents();
    setTitle(APP_NAME + " v" + APP_VERSION);
    cmbPattern.removeAllItems();
    cmbPattern.addItem("Случайное число");
    cmbPattern.addItem("Нумерация");
    cmbPattern.addItem("Нумерация с числа");
    cmbPattern.addItem("Префикс");
    cmbPattern.addItem("Суффикс");
    cmbPattern.addItem("Слово + номер");
    cmbPattern.addItem("Удаление подстроки");
    cmbPattern.addItem("Удаление N символов");

    cmbSide.removeAllItems();
    cmbSide.addItem("С начала");
    cmbSide.addItem("С конца");
    
    new FolderDropHandler(pnlDropSource, this::handleSourceFolderSelected);
    new FolderDropHandler(pnlDropDest, this::handleDestFolderSelected);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChooseFolder = new javax.swing.JButton();
        lblFolderPath = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList<>();
        btnRename = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnChooseDest = new javax.swing.JButton();
        lblDestPath = new javax.swing.JLabel();
        cmbPattern = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtInputText = new javax.swing.JTextField();
        lblInputText = new javax.swing.JLabel();
        txtCharCount = new javax.swing.JTextField();
        cmbSide = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pnlDropSource = new javax.swing.JPanel();
        lblDropSourceHint = new javax.swing.JLabel();
        pnlDropDest = new javax.swing.JPanel();
        lblDropDestHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 74, 195));

        btnChooseFolder.setText("Выбрать папку");
        btnChooseFolder.addActionListener(this::btnChooseFolderActionPerformed);

        lblFolderPath.setText("Папка не выбрана");

        listFiles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listFiles);

        btnRename.setText("Переименовать");
        btnRename.addActionListener(this::btnRenameActionPerformed);

        lblStatus.setText("Готово");

        btnChooseDest.setText("Выбрать папку для копий");
        btnChooseDest.addActionListener(this::btnChooseDestActionPerformed);

        lblDestPath.setText("Папка для копий не выбрана");

        cmbPattern.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPattern.addActionListener(this::cmbPatternActionPerformed);

        jLabel1.setText("Способ переименования");

        txtInputText.setText(" ");

        lblInputText.setText("Текст для паттернов");

        txtCharCount.setText("Кол-во символов");

        cmbSide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Сторона");

        pnlDropSource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDropSourceHint.setText("Перетащи папку сюда");

        javax.swing.GroupLayout pnlDropSourceLayout = new javax.swing.GroupLayout(pnlDropSource);
        pnlDropSource.setLayout(pnlDropSourceLayout);
        pnlDropSourceLayout.setHorizontalGroup(
            pnlDropSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDropSourceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblDropSourceHint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDropSourceLayout.setVerticalGroup(
            pnlDropSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDropSourceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDropSourceHint)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlDropDest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDropDestHint.setText("Перетащи папку сюда");

        javax.swing.GroupLayout pnlDropDestLayout = new javax.swing.GroupLayout(pnlDropDest);
        pnlDropDest.setLayout(pnlDropDestLayout);
        pnlDropDestLayout.setHorizontalGroup(
            pnlDropDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDropDestLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblDropDestHint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDropDestLayout.setVerticalGroup(
            pnlDropDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDropDestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDropDestHint)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRename, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCharCount, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(cmbSide, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(cmbPattern, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDestPath, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblInputText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnChooseFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(pnlDropSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChooseDest, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(pnlDropDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDropSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChooseFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFolderPath)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDropDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChooseDest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDestPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInputText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCharCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRename)
                    .addComponent(cmbSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void handleSourceFolderSelected(File folder) {
        selectedSourceFolder = folder;
        lblFolderPath.setText(folder.getAbsolutePath());
        loadFilesIntoList(folder);
    }

    private void handleDestFolderSelected(File folder) {
        selectedDestFolder = folder;
        lblDestPath.setText(folder.getAbsolutePath());
    }

    private void btnChooseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFolderActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fileChooser.setDialogTitle("Выберите исходную папку");

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        handleSourceFolderSelected(fileChooser.getSelectedFile());
    }
    }//GEN-LAST:event_btnChooseFolderActionPerformed

    private void btnRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameActionPerformed
    if (selectedSourceFolder == null) {
        lblStatus.setText("Сначала выберите исходную папку");
        return;
    }
    if (selectedDestFolder == null) {
        lblStatus.setText("Сначала выберите папку для копий");
        return;
    }

    File[] files = selectedSourceFolder.listFiles();
if (files == null || files.length == 0) {
    lblStatus.setText("В исходной папке нет файлов");
    return;
}

sortFilesNaturally(files);

    String timestamp = LocalDateTime.now().format(
            DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss"));
    File outputFolder = new File(selectedDestFolder, "renamed_" + timestamp);

    if (!outputFolder.mkdirs()) {
        lblStatus.setText("Не удалось создать папку для копий");
        return;
    }

     RenameStrategy strategy = createStrategy();
     if (strategy == null) {
       lblStatus.setText("Выберите способ переименования");
      return;
     }

    int copiedCount = 0;
    int errorCount = 0;
    int index = 1;

    for (File f : files) {
        if (!f.isFile()) {
            continue;
        }

        String extension = "";
        String name = f.getName();
        int dotIndex = name.lastIndexOf('.');
        if (dotIndex > 0) {
            extension = name.substring(dotIndex);
        }

        String newName;
        File destFile;
        do {
            newName = strategy.generateName(f, index) + extension;
            destFile = new File(outputFolder, newName);
        } while (destFile.exists());

        try {
            Files.copy(f.toPath(), destFile.toPath());
            copiedCount++;
        } catch (IOException ex) {
            errorCount++;
            logger.log(java.util.logging.Level.WARNING, "Не удалось скопировать: " + f.getName(), ex);
        }

        index++;
    }

    lblStatus.setText("Скопировано: " + copiedCount
            + (errorCount > 0 ? ", ошибок: " + errorCount : "")
            + " → папка " + outputFolder.getName());
    }//GEN-LAST:event_btnRenameActionPerformed

    private void btnChooseDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseDestActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fileChooser.setDialogTitle("Выберите папку для копий");

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        handleDestFolderSelected(fileChooser.getSelectedFile());
    }
    }//GEN-LAST:event_btnChooseDestActionPerformed

    private void cmbPatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatternActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatternActionPerformed

    
    private void loadFilesIntoList(File folder) {
    DefaultListModel<String> model = new DefaultListModel<>();

    File[] files = folder.listFiles();

    if (files != null) {
        sortFilesNaturally(files);
        for (File f : files) {
            if (f.isFile()) {
                model.addElement(f.getName());
            }
        }
    }

    listFiles.setModel(model);
    lblStatus.setText("Найдено файлов: " + model.getSize());
}
    
    private void sortFilesNaturally(File[] files) {
    Arrays.sort(files, Comparator.comparing(File::getName, new NaturalOrderComparator()));
}
    
    private RenameStrategy createStrategy() {
    String selected = (String) cmbPattern.getSelectedItem();
    if (selected == null) {
        return null;
    }

    switch (selected) {
        case "Случайное число":
            return new RandomNumberStrategy();
        case "Нумерация":
            return new NumberingStrategy();
            case "Нумерация с числа": {
                String text = txtInputText.getText();
                if (text == null || text.isBlank()) {
                    return null;
                }
                try {
                    int start = Integer.parseInt(text.trim());
                    return new NumberingFromStrategy(start);
                } catch (NumberFormatException ex) {
                    return null;
                }
            }
        case "Префикс": {
            String text = txtInputText.getText();
            if (text == null || text.isBlank()) {
                return null;
            }
            return new PrefixStrategy(text);
        }
        case "Суффикс": {
            String text = txtInputText.getText();
            if (text == null || text.isBlank()) {
                return null;
            }
            return new SuffixStrategy(text);
        }
        case "Слово + номер": {
    String text = txtInputText.getText();
    if (text == null || text.isBlank()) {
        return null;
    }
    return new WordNumberStrategy(text);
}
case "Удаление подстроки": {
    String text = txtInputText.getText();
    if (text == null || text.isBlank()) {
        return null;
    }
    return new RemoveSubstringStrategy(text);
}
case "Удаление N символов": {
    int count;
    try {
        count = Integer.parseInt(txtCharCount.getText().trim());
    } catch (NumberFormatException ex) {
        return null;
    }
    if (count < 0) {
        return null;
    }
    String sideText = (String) cmbSide.getSelectedItem();
    RemoveCharsStrategy.Side side = "С начала".equals(sideText)
            ? RemoveCharsStrategy.Side.START
            : RemoveCharsStrategy.Side.END;
    return new RemoveCharsStrategy(count, side);
        }
        default:
            return null;
    }
}
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseDest;
    private javax.swing.JButton btnChooseFolder;
    private javax.swing.JButton btnRename;
    private javax.swing.JComboBox<String> cmbPattern;
    private javax.swing.JComboBox<String> cmbSide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDestPath;
    private javax.swing.JLabel lblDropDestHint;
    private javax.swing.JLabel lblDropSourceHint;
    private javax.swing.JLabel lblFolderPath;
    private javax.swing.JLabel lblInputText;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> listFiles;
    private javax.swing.JPanel pnlDropDest;
    private javax.swing.JPanel pnlDropSource;
    private javax.swing.JTextField txtCharCount;
    private javax.swing.JTextField txtInputText;
    // End of variables declaration//GEN-END:variables
}
